inherit_from: .rubocop_todo.yml

require:
  - rubocop-rspec
  - rubocop-inflector
  - ./config/inflections

AllCops:
  TargetRubyVersion: 2.3

Naming/FileName:
  Exclude:
    - lib/rubocop-inflector.rb

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
    - '*.gemspec'
Metrics/LineLength:
  Exclude:
    - '*.gemspec'
