inherit_from: .rubocop_todo.yml

require:
  - rubocop-rspec
  - rubocop-inflector
  - ./config/inflections

AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable

Naming/FileName:
  Exclude:
    - lib/rubocop-inflector.rb

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
    - '*.gemspec'

Layout/LineLength:
  Exclude:
    - '*.gemspec'
